name = "admin-dashboard"
compatibility_date = "2024-11-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "kaaf-db"
database_id = "ccbd8ad8-7ba3-4288-975e-ba09b8f0c499" # Provided by user
